[package]
name = "r-matrix-snowfall"
description = "A NixOS-themed matrix snowfall screensaver (Fork of rmatrix)"
version = "0.2.4"
edition = "2024"
authors = [
	"Lucas Rooyakkers <lucas.rooyakkers@protonmail.com>",
	"T.Sawyer <saylesss87@proton.me",
]
repository = "https://github.com/saylesss88/rmatrix-snowfall"
readme = "README.md"
keywords = ["rust", "terminal"]
homepage = "https://github.com/saylesss88/rmatrix-snowfall"

license = 'GPL-3.0-or-later'
exclude = ["result", "docs", "demo.gif", ".github", ".gitignore"]

[dependencies]
crossterm = "0.29.0"
rand = {version = "0.8.5", features = ["small_rng"]}
structopt = "0.3.26"
term_size = "0.3.2"
clap = {version = "4.5.54", features = ["derive"]}

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
